### ISSUE TITLE
Can I choose to generate OpenAPI 3.0 files instead of 2.0 ?

### ISSUE THREAD

**Issue by luisromeroaraya** [microsoft/fhir-codegen#148]
I've succesfully generated the swagger files from my server but they are all in version 2.0. I could convert them one by one using the Swagger Editor but I was wondering if I can do it directly from th codegen.

Thanks!

**Comment by GinoCanessa** [comment]
Hi Luis, have you tried using the `OpenApiVersion` setting?  It should be availabe in the UI as `OpenApiVersion` and is available in the CLI as part of `language-options`, e.g.:
`fhir-codegen --fhir-server-url http://example.org/fhir --language OpenApi --language-options OpenApi|OpenApiVersion=3`

**Comment by luisromeroaraya** [comment]
Thanks a lot Gino!  That's exactly the option I was looking for ;)
