### ISSUE TITLE
TypeScript_R2 - bug in QuestionnaireResponseGroup

### ISSUE THREAD

**Issue by bkaney** [microsoft/fhir-codegen#50]
### QuestionnaireResponseGroup

This...
```typescript
export interface QuestionnaireResponseGroup extends BackboneElement {
  /**
   * Reports can consist of complex nested groups.
   */
  group?: QuestionnaireGroup[];
```

should be this...
```typescript
export interface QuestionnaireResponseGroup extends BackboneElement {
  /**
   * Reports can consist of complex nested groups.
   */
  group?: QuestionnaireResponseGroup[];
```

BTW - This was the only bug I found in R2 :)

**Comment by GinoCanessa** [comment]
Thanks for finding and reporting!  Fixed in commit: [cbe505c92f78ed0de9fa5d209a5010610030ad8c](https://github.com/microsoft/fhir-codegen/commit/cbe505c92f78ed0de9fa5d209a5010610030ad8c), will push a new release once it's verified to be correct.
